import { FarmEstate, ProductItem, SensorNode, ProcessStep, TeamMember, BatchRecord, StoryArticle } from './types';
import greenValleyImg from './assets/images/estate_green_valley_1789614019356.jpg';
import sunriseFarmImg from './assets/images/estate_sunrise_farm_1789614031666.jpg';
import riverbendRanchImg from './assets/images/estate_riverbend_ranch_1789614043119.jpg';
import coastalFieldsImg from './assets/images/estate_coastal_fields_1789614065990.jpg';
import seedImg from './assets/images/process_seed_circle_1789613322515.jpg';
import soilImg from './assets/images/process_soil_clod_1789613336614.jpg';
import growthImg from './assets/images/process_growth_plant_1789613350059.jpg';
import harvestImg from './assets/images/process_harvest_tomatoes_1789613363075.jpg';
import distribImg from './assets/images/process_distrib_ship_1789613376943.jpg';

export const HERO_STATS = [
  { value: '12,500+', label: 'Acres Under Cultivation', sub: 'Across 4 strategic bioclimates' },
  { value: '180,000+', label: 'Annual Yield (Tons)', sub: 'Delivered to wholesale partners' },
  { value: '12+', label: 'Global Markets Served', sub: 'Direct intermodal trade routes' },
  { value: '25+', label: 'Years of Experience', sub: 'Pioneering soil science since 2001' },
  { value: '100%', label: 'Sustainable Practices', sub: 'Zero non-renewable soil depletion' },
];

export const PRODUCT_CATEGORIES = [
  {
    id: 'grains',
    name: 'Grains',
    desc: 'High-yield, nutrient-rich',
    longDesc: 'Ancient heirloom and modern resilient grains cultivated with organic soil enrichment.',
    icon: 'Wheat',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
    count: '3 Varieties',
  },
  {
    id: 'fruits',
    name: 'Fruits',
    desc: 'Fresh, seasonal, premium',
    longDesc: 'Sun-ripened orchard fruits including Hass avocados, citrus, and stone fruits.',
    icon: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    count: '8 Orchards',
  },
  {
    id: 'vegetables',
    name: 'Vegetables',
    desc: 'Wholesome & nutritious',
    longDesc: 'Vibrant vine tomatoes, leafy brassicas, and root varieties nurtured under precision drip lines.',
    icon: 'Carrot',
    imageUrl: 'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&w=800&q=80',
    count: '14 Varieties',
  },
  {
    id: 'livestock',
    name: 'Livestock',
    desc: 'Healthy & responsibly raised',
    longDesc: 'Ethically pastured Black Angus and heritage cattle raised on rotational regenerative grass.',
    icon: 'Beef',
    imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=800&q=80',
    count: 'Pasture Raised',
  },
  {
    id: 'nursery',
    name: 'Nursery & Seedlings',
    desc: 'Strong roots, brighter future',
    longDesc: 'Micro-propagated rootstock and certified disease-free seedlings for commercial farms.',
    icon: 'Sprout',
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    count: '120k Seedlings/mo',
  },
  {
    id: 'specialty',
    name: 'Specialty Crops',
    desc: 'Unique, high-value',
    longDesc: 'Organically certified culinary herbs, microgreens, and medicinal botanical extracts.',
    icon: 'Flower2',
    imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=800&q=80',
    count: 'Bespoke Orders',
  },
];

export const FEATURED_PRODUCTS: ProductItem[] = [
  {
    id: 'wheat-gold',
    name: 'Heritage Golden Wheat',
    category: 'Grains',
    subtitle: 'High-yield, nutrient-rich durum',
    description: 'Slow-ripened durum wheat grown with cold-winter acclimation. High protein content with exceptional milling quality.',
    yieldPerAcre: '4.8 Tons / Acre',
    harvestSeason: 'Late Summer (August)',
    originEstate: 'Green Valley Estate',
    certifications: ['Non-GMO Verified', 'RegenAg Certified'],
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'vine-tomatoes',
    name: 'Vine-Ripened Cluster Tomatoes',
    category: 'Vegetables',
    subtitle: 'Sweet, dense & mineral-rich',
    description: 'Grown in high-tech geothermal glasshouses using predatory bio-controls instead of chemical pesticides.',
    yieldPerAcre: '32 Tons / Acre',
    harvestSeason: 'Year-Round Controlled',
    originEstate: 'Coastal Fields',
    certifications: ['Global G.A.P.', 'USDA Organic Equivalent'],
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'hass-avocados',
    name: 'Cold-Pressed Hass Avocados',
    category: 'Fruits',
    subtitle: 'Creamy high-oil culinary grade',
    description: 'Cultivated on ocean-facing terraced slopes with natural coastal fog irrigation and solar-supplemented pumps.',
    yieldPerAcre: '6.2 Tons / Acre',
    harvestSeason: 'Spring to Early Summer',
    originEstate: 'Sunrise Farm',
    certifications: ['Fair Trade Agriculture', 'Carbon Neutral Farm'],
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'pasture-cattle',
    name: 'Rotational Pasture Cattle',
    category: 'Livestock',
    subtitle: '100% Grass-fed Black Angus',
    description: 'Raised with high-frequency pasture rotation that restores native perennial prairie root structures.',
    yieldPerAcre: 'Regenerative Grass Habitat',
    harvestSeason: 'Year-Round Sustainable Rotation',
    originEstate: 'Riverbend Ranch',
    certifications: ['Animal Welfare Approved', 'Grass-fed Certified'],
    imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'organic-herbs',
    name: 'Medicinal & Culinary Herbs',
    category: 'Specialty Crops',
    subtitle: 'High terpene concentration',
    description: 'Thyme, rosemary, and mountain lavender harvested in dawn dew to lock in essential aromatic oils.',
    yieldPerAcre: '1.4 Tons / Acre',
    harvestSeason: 'Spring to Autumn',
    originEstate: 'Sunrise Farm',
    certifications: ['Biodynamic Demeter', 'ISO 22000'],
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
  },
];

export const SMART_FARM_SENSORS: SensorNode[] = [
  {
    id: 'soil-moisture',
    title: 'Soil Moisture',
    value: '68%',
    subtext: 'Optimal Zone (65-72%)',
    status: 'optimal',
    icon: 'Droplets',
    x: 35,
    y: 18,
    details: 'Depth probes at 15cm & 45cm indicate balanced water retention with zero runoff loss.',
  },
  {
    id: 'crop-health',
    title: 'Crop Health',
    value: 'Good (NDVI 0.88)',
    subtext: 'Chlorophyll Density High',
    status: 'optimal',
    icon: 'Activity',
    x: 48,
    y: 16,
    details: 'Multispectral drone imaging confirms vigorous canopy growth across all 24 cultivation zones.',
  },
  {
    id: 'weather',
    title: 'Microclimate',
    value: '24°C',
    subtext: 'Humidity 54% • Wind 6km/h',
    status: 'optimal',
    icon: 'CloudSun',
    x: 72,
    y: 18,
    details: 'Stable daytime transpiration conditions. Zero frost or extreme thermal risk projected for next 7 days.',
  },
  {
    id: 'irrigation',
    title: 'Subsurface Drip',
    value: 'Active (Zone 4)',
    subtext: '4.2 L/min Precision Metered',
    status: 'active',
    icon: 'Radio',
    x: 88,
    y: 32,
    details: 'Automated pulsing algorithm active based on evapotranspiration deficit calculations.',
  },
  {
    id: 'solar-power',
    title: 'Solar & Clean Energy',
    value: '+12%',
    subtext: 'Grid Positive Generation',
    status: 'active',
    icon: 'Sun',
    x: 46,
    y: 62,
    details: 'Agrivoltaic arrays mounted above shade crops generate 112% of total daily irrigation pump demand.',
  },
  {
    id: 'yield-forecast',
    title: 'Yield Forecast',
    value: '+12%',
    subtext: 'Above 5-Year Benchmark',
    status: 'optimal',
    icon: 'TrendingUp',
    x: 90,
    y: 65,
    details: 'Predictive neural model projects 184,200 metric tons total seasonal output across all farm parcels.',
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    stepNumber: '01',
    title: 'Seed',
    tagline: 'High-quality, resilient varieties',
    description: 'We source and propagate non-GMO, heritage seeds selected for natural drought tolerance, nutrient density, and flavor profiles.',
    metric: '99.4% Germination Rate',
    duration: 'Week 1 - 2',
    imageUrl: seedImg,
  },
  {
    stepNumber: '02',
    title: 'Soil',
    tagline: 'Enriched for optimal growth',
    description: 'Custom biochar and compost teas nourish native mycorrhizal fungi networks, maximizing mineral absorption without synthetic salts.',
    metric: '4.2% Organic Matter',
    duration: 'Pre-Planting Cycle',
    imageUrl: soilImg,
  },
  {
    stepNumber: '03',
    title: 'Growth',
    tagline: 'Nurtured with precision care',
    description: 'Continuous monitoring by automated drones and IoT field telemetry delivers exactly what plants need, when they need it.',
    metric: '35% Water Savings',
    duration: 'Weeks 3 - 12',
    imageUrl: growthImg,
  },
  {
    stepNumber: '04',
    title: 'Harvest',
    tagline: 'At the peak of quality',
    description: 'Crops are hand-selected and gathered at peak brix and oil content to preserve natural aroma, sweetness, and shelf stability.',
    metric: 'Zero Over-Ripe Loss',
    duration: 'Peak Brix Window',
    imageUrl: harvestImg,
  },
  {
    stepNumber: '05',
    title: 'Distribution',
    tagline: 'Delivered to global markets',
    description: 'Integrated cold-chain packaging and rapid intermodal freight transport fresh produce worldwide within strict temperature parameters.',
    metric: '< 24hr Port Transit',
    duration: 'Continuous Fleet',
    imageUrl: distribImg,
  },
];

export const FARM_ESTATES: FarmEstate[] = [
  {
    id: 'green-valley',
    name: 'Green Valley Estate',
    acres: 1850,
    crops: ['Grains', 'Vegetables'],
    location: 'Sacramento Delta Valley, California',
    coordinates: [38.3004, -121.5878],
    xPercent: 27,
    yPercent: 48,
    climate: 'Mediterranean Alluvial',
    elevation: '45m Above Sea Level',
    soilType: 'Deep River Silty Loam',
    certifications: ['USDA Organic', 'RegenAg Certified'],
    imageUrl: greenValleyImg,
  },
  {
    id: 'sunrise-farm',
    name: 'Sunrise Farm',
    acres: 2400,
    crops: ['Fruits', 'Specialty'],
    location: 'Okanagan Sunbelt Region',
    coordinates: [49.888, -119.496],
    xPercent: 37,
    yPercent: 42,
    climate: 'Semi-Arid Valley Plateau',
    elevation: '380m Above Sea Level',
    soilType: 'Volcanic Mineral Clay Loam',
    certifications: ['Global G.A.P.', 'Bee Friendly Farming'],
    imageUrl: sunriseFarmImg,
  },
  {
    id: 'riverbend-ranch',
    name: 'Riverbend Ranch',
    acres: 3250,
    crops: ['Livestock', 'Forage'],
    location: 'High Plains Pampas Basin',
    coordinates: [-34.6037, -58.3816],
    xPercent: 31,
    yPercent: 72,
    climate: 'Temperate Perennial Grassland',
    elevation: '120m Above Sea Level',
    soilType: 'Mollisol Humus-Rich Black Earth',
    certifications: ['Grass-fed Alliance', 'Carbon Sequestration Tier 1'],
    imageUrl: riverbendRanchImg,
  },
  {
    id: 'coastal-fields',
    name: 'Coastal Fields',
    acres: 1980,
    crops: ['Vegetables', 'Herbs'],
    location: 'Salinas Coastal Fog Belt',
    coordinates: [36.6777, -121.6555],
    xPercent: 22,
    yPercent: 52,
    climate: 'Maritime Microclimate',
    elevation: '15m Above Sea Level',
    soilType: 'Sandy Loam with High Porosity',
    certifications: ['Demeter Biodynamic', 'ISO 14001'],
    imageUrl: coastalFieldsImg,
  },
];

export const SUSTAINABILITY_METRICS = [
  {
    id: 'water',
    title: 'Water Stewardship',
    value: 78,
    unit: '%',
    highlight: 'Efficient use & recycling',
    description: 'Subsurface micro-drip irrigation and closed-loop rainwater retention systems reduce freshwater draw by 78% relative to regional conventional benchmarks.',
    color: '#38bdf8',
  },
  {
    id: 'soil',
    title: 'Soil Health',
    value: 64,
    unit: '%',
    highlight: 'Improvement in soil quality',
    description: 'Microbial biochar inoculation and cover-cropping protocols increased soil organic matter and active fungal mycorrhizae by 64% over four harvest cycles.',
    color: '#4ade80',
  },
  {
    id: 'regenerative',
    title: 'Regenerative Practices',
    value: 52,
    unit: '%',
    highlight: 'Land under regenerative management',
    description: 'Over 6,500 continuous acres managed under verified holistic regenerative grazing, multi-species cover crops, and minimal tillage.',
    color: '#22c55e',
  },
  {
    id: 'biodiversity',
    title: 'Biodiversity',
    value: 36,
    unit: '%',
    highlight: 'Increase in native species',
    description: 'Dedicated hedgerows, pollinator corridors, and wetlands have fostered a 36% rise in native bird, pollinator, and predatory insect populations.',
    color: '#a3e635',
  },
  {
    id: 'energy',
    title: 'Renewable Energy',
    value: 42,
    unit: '%',
    highlight: 'From clean energy sources',
    description: 'Onsite agrivoltaic arrays, agricultural biomass gasification, and solar-powered cold hubs satisfy 42% of total enterprise electrical footprint.',
    color: '#fbbf24',
  },
];

export const TECH_FEATURES = [
  {
    id: 'drone',
    title: 'Drone Crop Monitoring',
    subtitle: 'Real-time field analysis',
    description: 'Autonomous multi-rotor drones equipped with multispectral sensors map canopy vigor, thermal stress, and pest incursions at 2cm/pixel resolution.',
    badge: 'Autonomous Flight',
    icon: 'Plane',
  },
  {
    id: 'satellite',
    title: 'Satellite Imagery',
    subtitle: 'Large-scale insights',
    description: 'High-revisit synthetic aperture radar and optical satellites track regional evapotranspiration and biomass indices across millions of square meters.',
    badge: 'Sentinel & Planet Labs',
    icon: 'Satellite',
  },
  {
    id: 'ai',
    title: 'AI Crop Analytics',
    subtitle: 'Smarter decisions',
    description: 'Proprietary machine learning models cross-correlate 20 years of historical yield data with hyper-local sensor telemetry to optimize nitrogen and water timing.',
    badge: 'Neural Yield Predictor',
    icon: 'Cpu',
  },
  {
    id: 'irrigation',
    title: 'Smart Irrigation',
    subtitle: 'Water efficiency',
    description: 'Variable-rate precision valves respond dynamically to soil tension sensors and real-time microclimate vapor pressure deficit calculations.',
    badge: 'IoT Drip Grid',
    icon: 'Gauge',
  },
  {
    id: 'traceability',
    title: 'Traceability',
    subtitle: 'From farm to market',
    description: 'Cryptographically hashed batch logs document seed lineage, field coordinates, harvest timestamp, and unbroken cold-chain logistics.',
    badge: 'Cryptographic Ledger',
    icon: 'QrCode',
  },
];

export const TRACEABILITY_STEPS = [
  { step: '01', title: 'Harvest Batch', subtitle: 'ID & Tracking', icon: 'Tag' },
  { step: '02', title: 'Origin', subtitle: 'Farm Details', icon: 'MapPin' },
  { step: '03', title: 'Variety', subtitle: 'Crop Information', icon: 'Leaf' },
  { step: '04', title: 'Quality Checks', subtitle: 'Lab Testing', icon: 'ShieldCheck' },
  { step: '05', title: 'Processing', subtitle: 'Sorting & Grading', icon: 'Layers' },
  { step: '06', title: 'Packaging', subtitle: 'Secure & Fresh', icon: 'Box' },
  { step: '07', title: 'Destination', subtitle: 'Global Markets', icon: 'Globe' },
];

export const SAMPLE_BATCHES: Record<string, BatchRecord> = {
  'AF-24157': {
    batchId: 'AF-24157',
    productName: 'Hass Avocado',
    variety: 'Hass Extra Select A+',
    estate: 'Green Valley Estate (Sector 4B)',
    harvestDate: 'Apr 12, 2026',
    packDate: 'Apr 13, 2026',
    brixLevel: '24.2% Dry Matter (High Oil)',
    pesticideResidue: '0.00 ppm (Clean Lab Certified)',
    tempControlled: '5.2°C Constant Cold Chain',
    verified: true,
  },
  'AF-99821': {
    batchId: 'AF-99821',
    productName: 'Heritage Golden Wheat',
    variety: 'Hard Red Winter Durum',
    estate: 'Riverbend Ranch (North Field)',
    harvestDate: 'Aug 28, 2026',
    packDate: 'Aug 30, 2026',
    brixLevel: '14.8% High Gluten Protein',
    pesticideResidue: 'Zero Synthetic Chemicals Detected',
    tempControlled: '18.0°C Dry Aerated Silo',
    verified: true,
  },
  'AF-33104': {
    batchId: 'AF-33104',
    productName: 'Vine Cluster Tomatoes',
    variety: 'Campari Sweet Heritage',
    estate: 'Coastal Fields (Glasshouse C)',
    harvestDate: 'Sep 14, 2026',
    packDate: 'Sep 15, 2026',
    brixLevel: '8.4° Brix (Super Sweet)',
    pesticideResidue: '100% Bio-Control Protected',
    tempControlled: '11.5°C Precision Humidity Pack',
    verified: true,
  },
};

export const EXPORT_REGIONS = [
  { name: 'North America', status: 'Active Direct', routes: 'Pacific & Atlantic Corridors', volume: '62,000 Tons/yr' },
  { name: 'Europe', status: 'Active Direct', routes: 'Rotterdam & Hamburg Terminals', volume: '48,000 Tons/yr' },
  { name: 'Asia', status: 'Active Direct', routes: 'Yokohama, Shanghai, Singapore Hubs', volume: '42,000 Tons/yr' },
  { name: 'Africa', status: 'Strategic Partner', routes: 'Mediterranean & Cape Maritime', volume: '14,000 Tons/yr' },
  { name: 'Latin America', status: 'Active Direct', routes: 'Panama Canal Transshipment', volume: '14,000 Tons/yr' },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Dr. Elena Carter',
    role: 'Chief Agronomist',
    credentials: 'Ph.D. Plant & Soil Sciences, UC Davis',
    bio: 'Oversees microbiological soil diagnostics and regenerative crop rotation protocols across all 12,500 acres.',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'James Miller',
    role: 'Farm Manager',
    credentials: '22 Years Field Leadership',
    quote: "Agriculture isn't just about growing crops; it's about growing opportunities.",
    bio: 'Leads our on-the-ground estate operations, machinery maintenance, and seasonal harvest logistics.',
    imageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'Sophia Kim',
    role: 'Sustainability Lead',
    credentials: 'M.Sc. Environmental Engineering',
    bio: 'Directs our carbon sequestration monitoring, biodiversity buffer corridors, and solar agrivoltaic integration.',
    imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
  },
  {
    name: 'David Brooks',
    role: 'Operations Director',
    credentials: 'Global Cold-Chain Logistics Specialist',
    bio: 'Coordinates refrigerated freight, maritime shipping routes, and wholesale commodity contracts worldwide.',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=600&q=80',
  },
];

export const FIELD_STORIES: StoryArticle[] = [
  {
    id: 'soil-to-success',
    title: 'From Soil to Success',
    category: 'Regenerative Farming',
    readTime: '4 min read',
    date: 'August 2026',
    excerpt: 'Improving soil health for higher yields without chemical dependency.',
    content: 'By replacing synthetic fertilizers with active fungal compost teas and multi-species root covers, our Sacramento fields experienced a 24% boost in soil organic matter over four years, while increasing moisture retention by over 30 days during dry spells.',
    imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'seasonal-progress',
    title: 'Seasonal Progress: Growth Through Every Season',
    category: 'Agritech Innovation',
    readTime: '6 min read',
    date: 'September 2026',
    excerpt: 'How predictive microclimate algorithms shield high-value specialty crops from unseasonal frost and heat waves.',
    content: 'Using localized meteorological micro-stations and thermal drone flights, our teams anticipate frost hours 36 hours in advance, deploying targeted water-misting insulation that preserves delicate blossoms without losing a single hectare of fruit.',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
  },
];

export const PARTNERS = [
  { name: 'AgriTrade Global', type: 'Commodity Trading' },
  { name: 'GreenPath Logistics', type: 'Zero-Emission Freight' },
  { name: 'TerraFoods Corp', type: 'Organic Distribution' },
  { name: 'HarvestCo International', type: 'Retail Wholesale' },
  { name: 'Global Markets Alliance', type: 'Export Terminal' },
];

export const FAQS = [
  {
    q: 'How does AgriFuture ensure 100% sustainable agricultural practices?',
    a: 'We combine closed-loop drip irrigation, rotational cover cropping, native pollinator corridors, zero synthetic nitrogen run-off protocols, and agrivoltaic clean energy generation. Every parcel is verified annually by third-party regenerative standards.',
  },
  {
    q: 'Can international buyers order custom crop batches or forward contracts?',
    a: 'Yes. We provide forward contracting for grains, high-grade fruits, and specialty produce. All consignments include full batch traceability certificates, customs phytosanitary clearance, and cold-chain temperature telemetry.',
  },
  {
    q: 'What makes your Farm Intelligence system different from typical farm software?',
    a: 'Our platform integrates real-time subsurface soil probes, multispectral drone imagery, and predictive neural network yield forecasting directly into automated irrigation gates and field machinery dispatch.',
  },
  {
    q: 'How can we visit or audit one of the AgriFuture farm estates?',
    a: 'We welcome institutional partners, buyers, and agricultural researchers for scheduled on-site audits and guided field walkthroughs at any of our four estates. Please submit an inquiry via our Partner With Us form.',
  },
];
